core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_app/urls.py
from django.urls import path
from my_app.views import contact_view,login_view,products_view,logout_view
app_name = 'my_app'
urlpatterns = [

    path('contact/',contact_view,name = 'contact'),
    path('login/',login_view,name = 'login'),
    path('logout/',login_view,name = 'logout'),
    path('products/',products_view,name = 'products'),


]

my_app/models.py
from django.db import models




class Contact(models.Model):
    name = models.CharField(max_length=255,verbose_name='bizimle elaqe')
 
    mail = models.CharField(max_length=255,verbose_name='mail')
    
    subject = models.CharField(max_length=255,verbose_name='movzu')
    mesage = models.CharField(max_length=255,verbose_name='mesage')



    def __str__(self):

     return self.name
    
    class Meta:
       ordering = ('name',) 
       verbose_name = 'bizim haqqimizda'
       verbose_name_plural = 'bizim haqqimizdakilar'


class Products(models.Model):
    card_title = models.CharField(max_length=255,verbose_name='card adi')
    description =models.TextField(verbose_name='bizim haqqimizda')
    image = models.ImageField(upload_to='media/',null=True,blank=True)



    def __str__(self):

     return self.card_title
    
    class Meta:
       ordering = ('card_title',) 
       verbose_name = 'bizim haqqimizda'
       verbose_name_plural = 'bizim haqqimizdakilar'

my_app/forms.py
from django import forms
from my_app.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'mail', 'mesage', 'subject')

    def __init__(self, *args, **kwargs):
        super(ContactForm , self).__init__(*args, **kwargs)
        for field in self.fields:

            self.fields[field].widget.attrs.update({'class':'form-control'})
            self.fields[field].required = True

            self.fields['name'].widget.attrs.update({'placeholder':'adiniz ve soyadiniz'})
            self.fields['mail'].widget.attrs.update({'placeholder':'E-mailiniz'})
            self.fields['subject'].widget.attrs.update({'placeholder':'movzu'})
            self.fields['mesage'].widget.attrs.update({'placeholder':'mesajlariniz','class':'message-box form-control'})
        

my_app/views.py
from django.shortcuts import redirect, render
from my_app.models import *
from my_app.forms import ContactForm
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

def contact_view(request):

    form = ContactForm()
    
    text = Contact.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            form.save()
           
    context = {

              'form':form,  
              'text':text, 

    }
    
    return render(request,'contact.html',context)


def products_view(request):

    obj = Products.objects.all()
    mycard = request.GET.get('mycard')
    if mycard is not None:
       obj = obj.filter(card_title__icontains = mycard)

    paginator = Paginator(obj, 1)
    page = request.GET.get('page', 1)
    p = paginator.get_page(page)

    try:
        p = paginator.page(page)
    except PageNotAnInteger:
        p = paginator.page(1)
    except EmptyPage:
        p = paginator.page(paginator.num_pages)

    context = {
        'obj':obj,
        'p':p
    }
    return render(request,'products.html',context)


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("my_app:products")
        
    context = {}

    return render(request, "login.html", context)

def logout_view(request):
    logout(request)
    return redirect("my_app:products")

templates/contact.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form"  method="POST">
                {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            
                          {{form.name}}
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            {{form.mail}}
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            {{form.subject}}
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            {{form.mesage}}
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>San Francisco, CA 94126, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@mdbootstrap.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="form2Example1" class="form-control" name="username" />
    <label class="form-label" for="form2Example1">Username</label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="password" name="pwd" id="form2Example2" class="form-control" />
    <label class="form-label" for="form2Example2">Password</label>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
        <label class="form-check-label" for="form2Example31"> Remember me </label>
      </div>
    </div>

    <div class="col">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
    </div>
  </div>

  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

  <!-- Register buttons -->
  <div class="text-center">
    <p>Not a member? <a href="#!">Register</a></p>
    <p>or sign up with:</p>
    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-facebook-f"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-google"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-twitter"></i>
    </button>

    <button type="button" class="btn btn-link btn-floating mx-1">
      <i class="fab fa-github"></i>
    </button>
  </div>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/products.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
  <form method="get">
  <div class="input-group">
    <div class="form-outline">
      <input name="mycard"  type="search" id="form1" class="form-control" />
      <label class="form-label" for="form1">Search</label>
    </div>
    <button type="submit" class="btn btn-primary">
      <i class="fas fa-search"></i>
    </button>
  </div>
</form>
<div class="row row-cols-3 g-3">
  <div class="col">
    {% for i in p %}
    <div class="card">
      <img src="{{i.image.url}}" class="card-img-top"
        alt="Hollywood Sign on The Hill" />
      <div class="card-body">
        <h5 class="card-title">{{i.card_title}}</h5>
        <p class="card-text">{{i.description}}
        </p>
        <span>
          {% if user.is_authenticated %}
          <button class="btn btn-warning">
            {{ user.username }}
          </button>
          <a href="{% url 'my_app:logout' %}">
          <button class="btn btn-danger">
            Logout
          </button>
        </a>
          {% endif %}
        </span>
      </div>
    </div>
     {% endfor %}
     <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if p.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{p.number|add:'-1'}}">Previous</a></li>
        {% endif %}
        {% if p.number > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{p.number|add:'-1'}}">{{p.number|add:'-1'}}</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="?page={{p.number}}">{{p.number}}</a></li>
        {% if p.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{p.number|add:'1'}}">{{ p.number|add:'1'}}</a></li>
        <li class="page-item"><a class="page-link" href="?page={{p.number|add:'1'}}">Next</a></li>
        {% endif %}
      </ul>
    </nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>